Commit thứ 6, 7/5
bizflycloud/internship-2021 pull request #1
Opened 2021-05-07 10:24 UTC by huynp1999

2021-05-07 15:41 UTC, greatbn requested changes

2021-05-07 15:41 UTC, greatbn commented on huynp/Linux/Basic-command.md
> +- `-s` thêm các chuỗi đằng sau số được đánh
Chụp các ví dụ cho các lệnh nhé

2021-05-07 15:41 UTC, greatbn commented on huynp/Linux/Filesystem/Disk-review.md
> +12868	/etc
Tương tự. A cần ảnh chụp minh hoạ. Hoặc copy screen để vào shell quote

2021-05-07 15:41 UTC, greatbn commented on huynp/Linux/Filesystem/Filesystem.md
> +- ext3: hậu bản của ext2, cung cấp khả năng nhật ký nhưng đã bị xóa bỏ từ kernel Linux 4.3
Hậu bản là gì?

2021-05-07 15:41 UTC, greatbn commented on huynp/Linux/Filesystem/Filesystem.md
> +- swap: không thực sự là 1 dạng file hệ thống, bởi cơ chế hoạt động khá khác biệt. Được sử dụng dưới dạng bộ nhớ ảo và được dùng bởi kernel để ghi thay đổi vào ổ cứng. Thông thường, nó chỉ được sử dụ
Swap là của ext ak?

2021-05-08 01:21 UTC, huynp1999 commented on huynp/Linux/Basic-command.md
> +- `-s` thêm các chuỗi đằng sau số được đánh
Vâng em sẽ bổ sung hết trong hôm nay ạ

2021-05-12 01:18 UTC, merged